# Generated by Django 3.0 on 2019-12-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('idClient', models.IntegerField()),
            ],
        ),
    ]
