# Generated by Django 3.0 on 2019-12-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='idClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients'),
        ),
    ]
