# Generated by Django 3.0 on 2019-12-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20191208_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='image',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='price',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='title',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='idProduct',
            field=models.CharField(max_length=255),
        ),
    ]
